version: '3.1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    container_name: keycloak
    restart: always
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      start-dev
