registry:
  container_name: redis-ui
  image: patrikx3/p3x-redis-ui:latest
  ports:
    - 7843:7843
  volumes:
    # here you can set your own /home/user/p3x-redis-ui-settings folder
    - ./settings:/settings
