version: '3.1'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./key.pem:/usr/nginx/key.pem
      - ./cert.pem:/usr/nginx/cert.pem
    network_mode: host
